rvm: '2.6.0'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

services:
  - postgresql

before_script:
  - psql -c 'create database travis_chitter_test;' -U postgres

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
